#tomcat端口号 根路径配置
server:
  port: 8080
  context-path: /allinpay

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置该过滤器StatFilter druid后台才能看到SQL监控记录
    filters: stat,wall,slf4j,config
    #connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL4bOnHeX9yIZv0t3i+WPsMszD01jpEEsHbdLY2Sy9akFSe0ShkLwelz/s/EP2mVpLe3V3stSG0/lecXDRA1RGUCAwEAAQ==

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.allinpay.repository.domain

# 分页配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#配置文件
config:
  path: resource.properties